### ISSUE TITLE
Add multi language support

### ISSUE THREAD

**Issue by JustinyAhin** [learn-anything/learn-anything#1238] opened 2017-12-29 12:20 UTC
Hi, 
I'm juste discovering the project, and the website. I think that it'll be very good if the website can be displayed in others language apart from English (French, for example).
Then, more people will be able to browse on the site if the interface is in their language. 
Thanks.

**Comment by nglgzz** [comment] 2017-12-30 20:23
Hey @JustinyAhin! Supporting other languages is definitely on the roadmap, but it will have to wait as there are some other improvements that are more urgent.

Just translating the interface is not enough, we also need to add the possibility to create resources on other languages, and filtering based on those languages (so that you don't get results for languages you don't understand). 

The problem is that we currently only have resources in English, and at the rate the resources are being added, the website would be quite useless in other languages. For this we first need to update the structure of the maps, so that they're intuitive and easier to use, and then we need to have some kind of fallback for topics that have little to no resources (we were thinking to add some automated suggestions here).

**Comment by JustinyAhin** [comment] 2017-12-31 00:43
Ok, right. Hope the others language wille be ready soon.
Thanks

**Comment by nikitavoloboev** [comment] 2018-05-24 23:38
I will close this for now as this is not our top priority currently but it is on our [roadmap](https://github.com/learn-anything/learn-anything/wiki/Roadmap) and we are developing the website with multi language support in mind.

Currently the focus is on new design though.

**Closed by nikitavoloboev** 2018-05-24 23:38 UTC
